//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poligonotiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arma
    {
        public int id_arma { get; set; }
        public string nombre_arma { get; set; }
        public string modelo { get; set; }
        public string foto { get; set; }
        public string numero_serie { get; set; }
    }
}
