//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poligonotiro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cliente
    {
        [Key]
        public int id_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public string documento { get; set; }
        public int telefono { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public string porte_arma { get; set; }
        public string registro_arma { get; set; }
        public int id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
