//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poligonotiro.Models
{
    using System.Data.Entity;

    public partial class poligonoEntities : DbContext
    {
        public poligonoEntities() : base("name=poligonoEntities") { }

        public static poligonoEntities Create()
        {
            return new poligonoEntities();
        }
    
        public virtual DbSet<arma> arma { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<linea_tiro> linea_tiro { get; set; }
        public virtual DbSet<reserva_web> reserva_web { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<supervisor> supervisor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<temporizador_linea> temporizador_linea { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
