//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poligonotiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporizador_linea
    {
        public int id_temporizador { get; set; }
        public int id_reserva_web { get; set; }
        public string funcionalidad { get; set; }
    
        public virtual reserva_web reserva_web { get; set; }
    }
}
